locator: internal/stage/validate_config.go
meta:
  function_list:
    - ValidateConfig
    - init
  import_files_list:
    - context
    - fmt
    - github.com/flarebyte/thoth-ostraca/internal/config
  language: go
