locator: internal/stage/validate_config_helpers.go
meta:
  function_list:
    - applyMinimalToMeta
    - deepCopyAny
  import_files_list:
    - github.com/flarebyte/thoth-ostraca/internal/config
  language: go
