locator: internal/config/parse_post_reduce_actions.go
meta:
  function_list:
    - parseDiffMetaSection
    - parsePersistMetaSection
    - parsePostMapSection
    - parseReduceSection
    - parseUpdateMetaSection
  import_files_list:
    - cuelang.org/go/cue
    - fmt
  language: go
